version: '3.8'

services:
  IdentityDb:
    container_name: 'ZawodowcyIdentity.Db'
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - zawodowcy

  # ZawodowcyIdentity:
  #   container_name: 'Zawodowcy.Identity'
  #   image: 'zawodowcy.identity'
  #   build:
  #     context: .
  #     dockerfile: src/Services/Identity/Identity.Api/Dockerfile
  #   ports:
  #     - "5006:5006"
  #   depends_on:
  #     - "IdentityDb"
  #   networks:
  #     - zawodowcy

networks:
  zawodowcy:
    driver: bridge