version: '3.8'

services:
  ZawodowcyIdentityDb:
    container_name: 'zawodowcy_dev_identity_db'
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default_database
    ports:
      - '5432:5432'
    networks:
      - zawodowcy
    
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq/
      - ./docker/rabbitmq/log:/var/log/rabbitmq
    networks:
      - zawodowcy

networks:
  zawodowcy:
    driver: bridge
