version: '3.8'

services:
  ZawodowcyIdentityDb:
    container_name: 'zawodowcy_dev_identity_db'
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - zawodowcy

  ZawodowcyIdentity:
    container_name: 'zawodowcy_dev_identity'
    image: 'zawodowcy_dev_identity'
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      PORT: 7234
      ConnectionStrings:IdentityDb: "Host=zawodowcy_dev_identity_db;Port=5432;Database=Postgres;Username=postgres;Password=postgres"
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.Api/Dockerfile
    ports:
      - "5006:80"
      - "7234:7234"
      - "3001:3000"
    depends_on:
      - "ZawodowcyIdentityDb"
    networks:
      - zawodowcy

networks:
  zawodowcy:
    driver: bridge
